schema_version: 20180708
name: accounting-get-account-uids
version: 0.0.2
runtime: docker
format: json
type: sync
timeout: 20
triggers:
- name: get-account-uids
  type: http
  source: /get-account-uids
